### ISSUE TITLE
Switching Loops: highlight new target loop with red frame

### ISSUE THREAD

**Issue by bwagner** [mobius-looper/mobius3#1]
Mobius 2.5 had a nice feature: When you set "Switch Quantize" to "Confirm Loop": Within one track, when doing NextLoop or PreviousLoop, the new target loop would be indicated by a red frame, while the currently playing loop had a white frame. Only after confirming the switch would the white frame move from the current loop to the new loop.

Mobius 3 currently doesn't indicate what the new target loop is.

Also Mobius 2.5 Would indicate textually in white what the current target loop would be.

**Comment by mobius-looper** [comment]
Yes, that's an oversight, easy to add back.

**Comment by bwagner** [comment]
fixed in build 14 (or before)
