### ISSUE TITLE
crash on playback at different resolution

### ISSUE THREAD

**Issue by majjam** [mobius-looper/mobius3#2]
self build @
#0949c09a27d22e5df89f90b769c9aec6af32685a
from Reaper VST3 Asio , Windows machine

1. set sound card to 48khz
2. start reaper
3. record track
4. save track
5. end reaper
6. set sound card to 96khz
7. start reaper 
8. load track
9. play back
=> crash

BTW thanks for resurrecting mobius

**Comment by mobius-looper** [comment]
Thanks for the report.  I'll look at this, but I'd prefer it if we manage bug reports on the forum at mobiuslooper.com.  That's where most of the activity is taking place.  Thanks, Jeff

**Comment by majjam** [comment]
OK i will use the forum in future.

**Comment by majjam** [comment]
Moved report to forum
